Added a nil check SecCertificateCopySubjectSummary
datatheorem/TrustKit pull request #250
Opened 2021-04-24 23:25 UTC by CraigSiemens

Fixes #249

2021-04-27 20:31 UTC, nabla-c0d3 commented on TrustKit/Pinning/ssl_pin_verifier.m
> +        }
Lets also log something like `TSKLog(@"Could not parse certificate subject");`

2021-04-27 20:32 UTC, nabla-c0d3 requested changes
Thanks for the fix! Just left a minor request.

2021-05-10 20:23 UTC, CraigSiemens commented
@nabla-c0d3 Could you take a look at this again when you have the chance?

2021-05-19 19:53 UTC, merged

2021-05-19 19:53 UTC, nabla-c0d3 commented
Thank you!