restore iOS 12 support
datatheorem/TrustKit pull request #297
Opened 2023-04-03 08:38 UTC by aj-dt

restore runtime support for iOS 12, tvOS 12, watchOS 4 and macOS 10.13.

Adds OS-sensitive versions for copying keys (`copyKey()`) and evaluating server trust (`evaluateCertificateChainTrust()`).

`copyKey()` calls `SecTrustCopyKey()` on iOS 14+ and `SecTrustCopyPublicKey()` on earlier OSs.

`evaluateCertificateChainTrust()` calls `SecTrustEvaluateWithError()` on iOS 12+ and `SecTrustEvaluate()` on earlier OSs.

Note that macOS, tvOS, watchOS have slightly different version thresholds.

One subtlety in the implementation lies in `evaluateCertificateChainTrust()` which effectively "returns" three values: the bool return value and the referenced parameters TrustResult and the NSError. Since `SecTrustEvaluateWithError()` and `SecTrustEvaluate()` return slightly different sets of these three values for the various possible scenarios, interpretation of these results is delicate and requires if conditions evaluating combinations of these values. I consider this complexity acceptable given that consumers of TrustKit are shielded from it. For validation of the current code we rely on the unit tests (which all pass). 

Note that with these changes support for **running** on iOS 12 and iOS 13 is restored, however **building** with old versions of Xcode may fail. In particular, the use of `@available(iOS 14.0)` likely introduces a requirement to build with Xcode >= 12 (the earliest Xcode to ship with iOS 14, see [here](https://developer.apple.com/support/xcode/))

2023-04-04 11:22 UTC, JuhaO81 commented
Thx for adding the support back! Much needed here :)

2023-04-05 04:12 UTC, aj-dt commented
@nabla-c0d3 removed the bool return value from `evaluateCertificateChainTrust()` following your suggestion. It turned out to be redundant with the error parameter, so now there is less opportunity to cofuse that return value as a signal that the cert is trusted and one must examine the trust result to know the details.

2023-04-05 12:31 UTC, nabla-c0d3 requested changes
One minor change but looks good overall. Thanks!

2023-04-05 12:31 UTC, nabla-c0d3 commented on TrustKit/Pinning/pinning_utils.m
> +            certificateEvaluationSucceeded = false;
I think this line can be removed?

2023-04-05 13:48 UTC, aj-dt commented on TrustKit/Pinning/pinning_utils.m
> +            certificateEvaluationSucceeded = false;
Done

2023-04-05 14:05 UTC, nabla-c0d3 approved these changes

2023-04-05 14:05 UTC, merged